#jugando con phython
#print("  ***********")
#print("  *         *")
#print("  *         *")
#print("  *         *")
#print("  *         *")
#print("  *         *")
#print("  ***********")
#print("       *")
#print("     *****")
#print("    *******")
#print("   *********")
#print("  ***********")
#print("  ___________")
#print("  |  _   _  |")
#print("  | |_| |_| |" ,"    ^^   ")
#print("  | °     ° |", "   ^^^^  "  )
#print("  ___________", "  ^^^^^^ ")
#print("  |  _   _  |", "   ^^^^  "  )
#print("  | |_| |_| |", "    ^^   ")
#print("  |   _____ |", "    ||")
#print("  |___|_|_|_|", "    ||")